rodizio = float(input("Qual foi o valor da conta?:"))
numerodePessoas = int(input ("Quantas pessoas irão dividir o rodizio?:"))
gorjeta = int(input("Qual a porcentagem da gorjeta? 15%,18% ou 20%:"))
porcentagem = (gorjeta/100)
valorGorjeta = (rodizio * porcentagem)
valorTotal = (rodizio + valorGorjeta)
porPessoa = (valorTotal / numerodePessoas)
print("O valor total da conta é: R$",valorTotal)
print("O valor por pessoa é: R$",porPessoa)
print("Obrigado pela preferência!")
print("Volte sempre!")
print("Até mais!")
