print("Getting to know you!")
myName = input("What's you name?: ")
myAge = input("How old are you? :")
print("Gee, that's REALLY OLD")
myFood = input("What's your favorite food?: ")
myMusic = input("What's your favorite music?: ")
myAdress = input("Where do you live?")

print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and your favorite food is")
print(myFood)
print("and your favorite music is")
print(myMusic)
print("Great place to live in")
print(myAdress)
print() 
print ("Have a great day!")